import Link from 'next/link';

import { Explorer } from '@/components/common/Explorer/Explorer';
import { Navigation } from '@/components/common/Navigation';
import { Sidebar } from '@/components/common/Sidebar';

export const metadata = {
  title: 'VSCode Luca Neves',
  description: 'Generated by create next app',
};

export default function VSCodeLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col w-full h-[55rem] p-2 pb-0 shadow-xl rounded-xl bg-brand-background-dark">
      <div className="flex items-start justify-between px-3 bg-brand-background">
        <div className="flex items-center gap-2 my-2">
          <Link href="/" className="w-3 h-3 bg-red-500 rounded-full" />
          <Link href="/" className="w-3 h-3 bg-yellow-500 rounded-full" />
          <div className="w-3 h-3 bg-green-500 rounded-full" />
        </div>
      </div>
      <div className="flex h-full">
        <Sidebar />
        <Explorer />
        <div className="flex flex-col w-full">
          <Navigation />
          {children}
        </div>
      </div>
    </div>
  );
}
