import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';

import { Providers } from '@/providers';

import { options } from './api/auth/[...nextauth]/route';
import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VSCode Luca Neves',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(options);
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Providers session={session}>
          <div className="relative z-10 items-center justify-center h-screen p-20 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
