import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from '@/providers';

import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VSCode Luca Neves',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Providers>
          <div className="relative flex z-10 items-center justify-center w-full min-h-[100vh] p-10 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
